---
name: Mark stale issues and pull requests

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@1e223db275d687790206a7acac4d1a11bd6fe629 # v10.4.0
        with:
          operations-per-run: 1000
          stale-issue-message: |
            Hello, to help manage issues we automatically close stale issues.

            This issue has been automatically marked as stale because it has not had activity for quite some time. If it is still relevant, leave a comment to keep it open.

            > This issue will be closed in 15 days if no further activity occurs.

            Thank you for your contributions.
          stale-pr-message: |
            Hello, this PR has been open for more than 28 days with no activity.

            If you think this is a mistake, please comment to keep this open. Thanks for contributing!

            > This PR will be closed in 15 days if no further activity occurs.
          exempt-issue-labels: 'keep open'
          exempt-pr-labels: 'keep open'
          close-issue-reason: 'not_planned'
          days-before-stale: 28
          days-before-close: 15
          stale-issue-label: 'not-planned'
          stale-pr-label: 'stale'
